version: "3.7"
services:

  gamemaster:
    build:
      context: ./src/GameMaster
    image: rynowak.azurecr.io/rochambot/gamemaster

  scoreboard:
    build:
      context: ./src/Scoreboard
    image: rynowak.azurecr.io/rochambot/scoreboard

  matchmaker:
    build:
      context: ./src/MatchMaker
    image: rynowak.azurecr.io/rochambot/matchmaker
    depends_on: 
      - gamemaster
      - robbybot

  robbybot:
    build:
      context: ./src/RobbyBot
    image: rynowak.azurecr.io/rochambot/robbybot
    depends_on: 
      - gamemaster
      
  rochambot:
    build:
      context: ./src/Rochambot
    image: rynowak.azurecr.io/rochambot/rochambot
    depends_on: 
      - gamemaster
      - matchmaker
      - scoreboard
    ports: 
      - "5000:80"