trigger:
  branches:
    include:
    - master
    - release/*
    - feature/*

pr:
  branches:
    include:
    - master
    - release/*
    - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install dotnet SDK'
  inputs:
    packageType: 'sdk'
    version: '3.0.100'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'rochambot.sln'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    releaseType: 'edge'

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'