trigger:
  branches:
    include:
    - master
    - release/*
    - feature/*

pr:
  branches:
    include:
    - master
    - release/*
    - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install dotnet SDK'
  inputs:
    packageType: 'sdk'
    version: '3.0.100'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'rochambot.sln'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    releaseType: 'edge'

- bash: |
    az login --service-principal --username $(AZ_APPID) --password $(AZ_PASSWORD) --tenant $(AZ_TENANTID)

- bash: |
    az acr login --name rynowak

- bash: |
    helm init --client-only
    az acr helm repo add --name rynowak

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'gamemaster'
    context: 'src/GameMaster'

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'matchmaker'
    context: 'src/MatchMaker'

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'robbybot'
    context: 'src/RobbyBot'

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'rochambot'
    context: 'src/Rochambot'

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'scoreboard'
    context: 'src/Scoreboard'