trigger:
  branches:
    include:
    - master
    - release/*
    - feature/*

pr:
  branches:
    include:
    - master
    - release/*
    - feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    echo "##vso[build.updatebuildnumber]$(git describe --tags)" 

- task: UseDotNet@2
  displayName: 'Install dotnet SDK'
  inputs:
    packageType: 'sdk'
    version: '3.0.100'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'rochambot.sln'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
    releaseType: 'edge'

- task: HelmInstaller@1
  inputs:
    helmVersionToInstall: 'latest'

- bash: |
    az login --service-principal --username $(AZ_APPID) --password $(AZ_PASSWORD) --tenant $(AZ_TENANTID)

- bash: |
    az acr login --name rynowak

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: rynowak.azurecr.io

- bash: |
    helm init

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'gamemaster'
    context: 'src/GameMaster'
    serviceConnection: rynowak.azurecr.io

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'matchmaker'
    context: 'src/MatchMaker'
    serviceConnection: rynowak.azurecr.io

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'robbybot'
    context: 'src/RobbyBot'
    serviceConnection: rynowak.azurecr.io

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'rochambot'
    context: 'src/Rochambot'
    serviceConnection: rynowak.azurecr.io

- template: build/templates/docker-build.yml
  parameters:
    repository: 'rynowak.azurecr.io/rochambot'
    image: 'scoreboard'
    context: 'src/Scoreboard'
    serviceConnection: rynowak.azurecr.io