apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamemaster
  labels:
    app: gamemaster
  annotations:
    actions.io/enabled: "true"
    actions.io/id: "gamemaster"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamemaster
  template:
    metadata:
      labels:
        app: gamemaster
    spec:
      containers:
      - name: gamemaster
        image: rynowak.azurecr.io/rochambot/gamemaster:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
