apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamemaster
  labels:
    app: gamemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamemaster
  template:
    metadata:
      labels:
        app: gamemaster
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "gamemaster"
        dapr.io/port: "80"
        dapr.io/config: "zipkin"
    spec:
      containers:
      - name: gamemaster
        image: rynowak.azurecr.io/rochambot/gamemaster:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
