apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
  labels:
    app: matchmaker
  annotations:
    actions.io/enabled: "true"
    actions.io/id: "matchmaker"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      labels:
        app: matchmaker
    spec:
      containers:
      - name: matchmaker
        image: rynowak.azurecr.io/rochambot/matchmaker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80