apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmaker
  labels:
    app: matchmaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmaker
  template:
    metadata:
      labels:
        app: matchmaker
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "matchmaker"
        dapr.io/port: "80"
        dapr.io/config: "zipkin"
    spec:
      containers:
      - name: matchmaker
        image: rynowak.azurecr.io/rochambot/matchmaker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80