apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: redis-master.kube-system.svc.cluster.local:6379
  - name: redisPassword
    value: WSiTDK5wjT
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master.kube-system.svc.cluster.local:6379
  - name: redisPassword
    value: WSiTDK5wjT
