apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  metadata:
  - name: redisHost
    value: rynowak-redis.redis.cache.windows.net:6379
  - name: redisPassword
    secretKeyRef:
      name: dapr-redis-secret
      key: redis-password
auth:
  secretStore: kubernetes
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: rynowak-redis.redis.cache.windows.net:6379
  - name: redisPassword
    secretKeyRef:
      name: dapr-redis-secret
      key: redis-password
auth:
  secretStore: kubernetes