apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gamemaster.fullname" . }}
  labels:
{{ include "gamemaster.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gamemaster.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gamemaster.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: {{ .Chart.Name }}
        dapr.io/port: "80"
        dapr.io/config: "zipkin"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
